name: fallacious_rooster
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: "^5.6.0"
  google_fonts: "^6.2.1"
  universal_html: "^2.2.4"
  multi_select_flutter: "^4.1.3"
  flutter_localizations:
    sdk: flutter
  intl: any
  adaptive_theme: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  
flutter_intl:
  enabled: true